name: Compile mod.io for Godot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-release-x64:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Windows Release x64
      run: cargo build --target x86_64-pc-windows-msvc --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-release-x64
        path: target/x86_64-pc-windows-msvc/release/mod_io.dll

  build-windows-debug-x64:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Windows Debug x64
      run: cargo build --target x86_64-pc-windows-msvc

    - name: Rename Debug Artifact
      run: |
        mkdir -p target/x86_64-pc-windows-msvc/debug/renamed
        mv target/x86_64-pc-windows-msvc/debug/mod_io.dll target/x86_64-pc-windows-msvc/debug/renamed/mod_io.debug.dll

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-debug-x64
        path: target/x86_64-pc-windows-msvc/debug/renamed/mod_io.debug.dll

  build-macos-release-x64:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install toolchain
      run: rustup target add x86_64-apple-darwin

    - name: Build macOS Release x64
      run: cargo build --target x86_64-apple-darwin --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-release-x64
        path: target/x86_64-apple-darwin/release/libmod_io.dylib

  build-macos-debug-x64:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install toolchain
      run: rustup target add x86_64-apple-darwin

    - name: Build macOS Debug x64
      run: cargo build --target x86_64-apple-darwin

    - name: Rename Debug Artifact
      run: |
        mkdir -p target/x86_64-apple-darwin/debug/renamed
        mv target/x86_64-apple-darwin/debug/libmod_io.dylib target/x86_64-apple-darwin/debug/renamed/libmod_io.debug.dylib

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-debug-x64
        path: target/x86_64-apple-darwin/debug/renamed/libmod_io.debug.dylib

  build-linux-release-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Linux Release
      run: cargo build --target x86_64-unknown-linux-gnu --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-release
        path: target/x86_64-unknown-linux-gnu/release/libmod_io.so
  
  build-linux-debug-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Linux Debug
      run: cargo build --target x86_64-unknown-linux-gnu

    - name: Rename Debug Artifact
      run: |
        mkdir -p target/x86_64-unknown-linux-gnu/debug/renamed
        mv target/x86_64-unknown-linux-gnu/debug/libmod_io.so target/x86_64-unknown-linux-gnu/debug/renamed/libmod_io.debug.so

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-debug
        path: target/x86_64-unknown-linux-gnu/debug/renamed/libmod_io.debug.so

  compress-and-upload:
    needs: 
      - build-windows-release-x64
      - build-windows-debug-x64
      - build-macos-release-x64
      - build-macos-debug-x64
      - build-linux-release-x64
      - build-linux-debug-x64
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Create zip file with all artifacts
      run: zip -r artifacts.zip artifacts

    - name: Upload Combined Artifact
      uses: actions/upload-artifact@v2
      with:
        name: combined-artifacts
        path: artifacts.zip
