name: Compile mod.io for Godot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-release-x64:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Windows Release x64
      run: cargo build --target x86_64-pc-windows-msvc --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-release-x64
        path: target/x86_64-pc-windows-msvc/release/mod_io.dll

  build-windows-release-x86:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Windows Release x86
      run: cargo build --target i686-pc-windows-msvc --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-release-x86
        path: target/i686-pc-windows-msvc/release/mod_io.dll

  build-windows-debug-x64:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Windows Debug x64
      run: cargo build --target x86_64-pc-windows-msvc

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-debug-x64
        path: target/x86_64-pc-windows-msvc/debug/mod_io.dll

  build-windows-debug-x86:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Windows Debug x86
      run: cargo build --target i686-pc-windows-msvc

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-debug-x86
        path: target/i686-pc-windows-msvc/debug/mod_io.dll

  build-macos-release-x64:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build macOS Release x64
      run: cargo build --target x86_64-apple-darwin --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-release-x64
        path: target/x86_64-apple-darwin/release/libmod_io.dylib

  build-macos-debug-x64:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build macOS Release x64
      run: cargo build --target x86_64-apple-darwin

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-release-x64
        path: target/x86_64-apple-darwin/debug/libmod_io.dylib

  build-linux-release-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Linux Release
      run: cargo build --target x86_64-unknown-linux-gnu --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-release
        path: target/x86_64-unknown-linux-gnu/release/libmod_io.so
  
  build-linux-debug-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build Linux Debug
      run: cargo build --target x86_64-unknown-linux-gnu

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-debug
        path: target/x86_64-unknown-linux-gnu/debug/libmod_io.so
  build-android-release-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: 'r23c'

    - name: Build Android Release x64
      run: cargo build --target aarch64-linux-android --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-release-x64
        path: target/aarch64-linux-android/release/libmod_io.so

  build-android-release-x86:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: 'r23c'

    - name: Build Android Release x86
      run: cargo build --target i686-linux-android --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-release-x86
        path: target/i686-linux-android/release/libmod_io.so

  build-android-debug-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: 'r23c'

    - name: Install target
      run: rustup target add aarch64-linux-android

    - name: Build Android Debug x64
      run: cargo build --target aarch64-linux-android

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-debug-x64
        path: target/aarch64-linux-android/debug/libmod_io.so

  build-android-debug-x86:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: 'r23c'

    - name: Install target
      run: rustup target add i686-linux-android

    - name: Build Android Debug x86
      run: cargo build --target i686-linux-android

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-debug-x86
        path: target/i686-linux-android/debug/libmod_io.so
