name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly]
        arch: [x64, x86]
        mode: [debug, release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build --target ${{ matrix.arch }}-unknown-${{ matrix.os }} --${{ matrix.mode }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
        path: target/${{ matrix.arch }}-unknown-${{ matrix.os }}/${{ matrix.mode }}/mod_io
