name: Rust

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64, x86]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build and test
      run: cargo build --target ${{ matrix.os }} --release

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-${{ matrix.arch }}-artifacts
        path: target/${{ matrix.os }}/release

  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust for Android
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal

    - name: Build for Android
      run: cargo build --target arm-linux-androideabi --release

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-artifacts
        path: target/arm-linux-androideabi/release
