name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        rust: [stable, nightly]
        arch: [x64, x86]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build --target ${{ matrix.arch }}-unknown-${{ matrix.os }} --release

    - name: Build Debug
      run: cargo build --target ${{ matrix.arch }}-unknown-${{ matrix.os }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-release
        path: target/${{ matrix.arch }}-unknown-${{ matrix.os }}/release/mod_io

    - name: Upload Artifact Debug
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-debug
        path: target/${{ matrix.arch }}-unknown-${{ matrix.os }}/debug/mod_io
